Add static test scripts
metal3-io/ironic-standalone-operator pull request #14
Opened 2024-03-25 16:48 UTC by Rozzii

In order to prepare the repository for CI integration

This commit:
- Adds a subset of the static analysis and formatting tools.
- Modifies the root Makefile to allow running gomod.sh
- aligns static test container wrapper scripts

I will align the code and the docs in multiple PRs to not create xK line PRs.

2024-03-26 06:16 UTC, tuminoid commented
> I will align the code and the docs in multiple PRs to not create xK line PRs.

Is there a lot of issues that would fail a test? Otherwise I'd suggest enabling Prow first, so each PR could be tested.

2024-03-26 09:56 UTC, dtantsur commented on Makefile
> +# Optiona are set to exit when a recipe line exits non-zero or a piped command fails.
Options

2024-03-26 09:57 UTC, dtantsur commented on Makefile
> +            aelf._logger.debug("boot image id is: " + str(image_id))
Unrelated changes

2024-03-26 09:57 UTC, dtantsur commented on Makefile
> +	cd $(TOOLS_DIR) && $(GO) mod tidy
Note that apis and tools are not separate modules here (yet?)

2024-03-26 09:58 UTC, dtantsur commented on go.mod
> +go 1.22.0
Please don't go to 1.22.0, it will break local development for virtual everyone. The main branch has 1.21 now.

2024-03-26 09:58 UTC, dtantsur commented on test/go.mod
> +go 1.22.0
Same here

2024-03-26 10:27 UTC, tuminoid reviewed
Some nits.

2024-03-26 10:27 UTC, tuminoid commented on Dockerfile
> +ARG BUILD_IMAGE=docker.io/golang:1.22@sha256:0b55ab82ac2a54a6f8f85ec8b943b9e470c39e32c109b766bbc1b801f3fa8d3b
Specify the patch version as well. `1.22` is moving tag.

2024-03-26 10:27 UTC, tuminoid commented on Makefile
> +GO_VERSION ?= 1.21.8
This is also mismatching versus Dockerfile. This is the right version to go-to as Dmitry pointed out.

2024-03-26 10:27 UTC, tuminoid commented on go.mod
> +go 1.22.0
Also going down to patch level is different from other repos, and will have effect on consumers. While it might be the right thing to do going down the line, we might need to agree on it and implement it the same way for all repos, IMO.

2024-03-26 10:27 UTC, tuminoid commented on hack/gomod.sh
> +        docker.io/golang:1.22 \
1.22 here too

2024-03-26 13:45 UTC, elfosardo commented on test/go.mod
> +toolchain go1.22.1
please remember to change toolchain version too

2024-03-27 10:00 UTC, dtantsur commented on test/go.mod
> +toolchain go1.22.1
I'd rather drop this `toolchain` instruction. I don't understand why Go is sometimes adding it, but it's not required.

2024-03-27 13:33 UTC, Rozzii commented on Dockerfile
> +ARG BUILD_IMAGE=docker.io/golang:1.22@sha256:0b55ab82ac2a54a6f8f85ec8b943b9e470c39e32c109b766bbc1b801f3fa8d3b
but I have added the sha, shouldn't that specify it explicitly?

2024-03-27 14:06 UTC, tuminoid commented on Dockerfile
> +ARG BUILD_IMAGE=docker.io/golang:1.22@sha256:0b55ab82ac2a54a6f8f85ec8b943b9e470c39e32c109b766bbc1b801f3fa8d3b
It does, but doesn't mean anything to humans, and some tools like Quay build will happily explode when those won't match later on. Also any tooling reading that doesn't need to do detective work to figure out which tag would it be.

2024-03-28 10:23 UTC, Rozzii commented on Makefile
> +GO_VERSION ?= 1.21.8
done

2024-03-28 10:26 UTC, Rozzii commented on Makefile
> +            aelf._logger.debug("boot image id is: " + str(image_id))
removed thanks

2024-03-28 10:26 UTC, Rozzii commented on Makefile
> +	cd $(TOOLS_DIR) && $(GO) mod tidy
I have removed the tool dir for the moment.

2024-03-28 11:01 UTC, tuminoid requested changes

2024-03-28 11:01 UTC, tuminoid commented on Makefile
> +SHELa = /usr/bin/env bash -o pipefail
Some weird typo here...

```suggestion
SHELL = /usr/bin/env bash -o pipefail
```

2024-03-28 11:11 UTC, Rozzii commented on Makefile
> +SHELa = /usr/bin/env bash -o pipefail
nice catch thanks, no clue how this happened.

2024-03-28 11:15 UTC, tuminoid commented on hack/ensure-go.sh
> +    minimum_go_version=go1.20
Should this be 1.21?

2024-03-28 11:15 UTC, tuminoid commented on hack/gomod.sh
> +        docker.io/golang:1.21.8 \
For hack scripts we don't specify patch version, so it will use the latest of the minor.

```suggestion
        docker.io/golang:1.21 \
```

2024-03-28 11:22 UTC, Rozzii commented on hack/ensure-go.sh
> +    minimum_go_version=go1.20
done

2024-03-28 11:22 UTC, Rozzii commented on hack/gomod.sh
> +        docker.io/golang:1.21.8 \
done

2024-03-28 11:25 UTC, tuminoid approved these changes
LGTM

2024-03-28 13:17 UTC, Rozzii commented
/retest

2024-03-28 13:18 UTC, Rozzii commented
/override markdownlint 
markdownlint fixes are in a separate PR let's ignore this.

2024-03-28 13:22 UTC, dtantsur commented
/approve

2024-03-28 13:23 UTC, merged