Add golangci-lint
metal3-io/ironic-standalone-operator pull request #94
Opened 2024-12-03 09:46 UTC by elfosardo

Closes https://github.com/metal3-io/ironic-standalone-operator/issues/71

2024-12-03 09:54 UTC, elfosardo commented
@tuminoid @dtantsur  I took the config from BMO which has the same version now, so the linters are the same, I see quite some errors, do we want to modify the linters or fix the errors? :smile:

2024-12-03 10:18 UTC, tuminoid commented
> @tuminoid @dtantsur I took the config from BMO which has the same version now, so the linters are the same, I see quite some errors, do we want to modify the linters or fix the errors? 😄

When we introduced golangci-lint in BMO/CAPM3 etc, we first enabled only the passing set of linters, commented the others out. Then PR by PR enabled those linters with required code fixes. This way the patches are reasonable and its clear why the changes are made.

2024-12-03 10:25 UTC, tuminoid commented on .github/workflows/golangci-lint.yml
> +    - name: Install libvirt
This is not needed in IRSO

2024-12-03 10:25 UTC, tuminoid commented on .golangci.yaml
> +  build-tags:
These are BMO tags

2024-12-03 10:25 UTC, tuminoid commented on .golangci.yaml
> +  enable:
Not too bad list of failures, we'd need to comment out:
- errcheck
- gci
- godot
- gosec
- revive
- unconvert
- unused
- whitespace
- nakedret

and out of those, we could turn back on:
- whitespace
- unused
- unconvert
- gosec

with a single line fix for each in this PR even, leaving only 5 disabled.

2024-12-03 10:25 UTC, tuminoid commented on .github/workflows/golangci-lint.yml
> +  push:
Trigger should be

```yaml
on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]
```

as seen in CAPM3. BMO linter is part of more strucutred actions setup, so it is not good example for triggers.

2024-12-03 16:48 UTC, elfosardo commented
\o/

2024-12-04 06:24 UTC, tuminoid reviewed
Thanks for adding it, looking great! One minor nit.

/approve

2024-12-04 06:24 UTC, tuminoid commented on pkg/ironic/ironic.go
> +		return // ignore
```suggestion
		return //nolint:nilerr
```
That should ignore it in more concise and consistent way.

Though this looks like it would also warrant proper fix. Returning nothing instead of two values is sketchy. It can be fixed in later PRs as well.

2024-12-04 08:09 UTC, elfosardo commented on pkg/ironic/ironic.go
> +		return // ignore
yes, honestly I forgot to change it with the one liner!
And I agree this should be fixed and not ignored, but it's not doing too much harm AFAICS
I'm planning to take care of the rest of the stuff we ignored commenting out the linters, I'll add this one to the list

2024-12-05 09:16 UTC, dtantsur commented on .golangci.yaml
> +      alias: metal3iov1alpha1
Btw this alias is no longer correct. After I've fixed the API group to "ironic", Kubebuilder generates `ironicv1alpha1`. We can merge this as it is and clean up later.

2024-12-05 09:17 UTC, dtantsur commented on .golangci.yaml
> +  - path: test/e2e
We don't have an e2e directory here.

2024-12-05 09:19 UTC, dtantsur commented on internal/controller/ironic_controller.go
> +	metal3iov1alpha1 "github.com/metal3-io/ironic-standalone-operator/api/v1alpha1"
Please don't make this change, I literally reverted this in BMO already.

2024-12-05 09:19 UTC, dtantsur commented on internal/controller/ironicdatabase_controller.go
> +	metal3iov1alpha1 "github.com/metal3-io/ironic-standalone-operator/api/v1alpha1"
Same here and in other files

2024-12-05 09:22 UTC, dtantsur commented on test/suite_test.go
> +		var podLogs io.ReadCloser
This entire change does not look valid to me. Especially using `defer` is the correct and idiomatic way to handle this case.

2024-12-05 09:23 UTC, dtantsur requested changes
Thanks for taking on this work!

I'd prefer we only enable linters that only pass and enable the rest separately. Many of the changes made here don't look valid to me.

2024-12-05 09:48 UTC, elfosardo commented
/unhold

2024-12-05 09:48 UTC, elfosardo commented on .golangci.yaml
> +      alias: metal3iov1alpha1
I've changed it to ironicv1alpha1
we'll clean up when enabling the importas linter

2024-12-05 09:55 UTC, elfosardo commented on test/suite_test.go
> +		var podLogs io.ReadCloser
considering that this is a test file it's probably not a big deal and we may ignore it, but my understanding is that using defer inside for loop is not recommended in general, it's exposed by the gocritic linter https://go-critic.com/overview.html#deferinloop

2024-12-05 09:56 UTC, elfosardo commented
@dtantsur I've simplified a lot this change, we can work on single linters one by one

2024-12-05 10:07 UTC, dtantsur approved these changes
/lgtm

Thanks!

2024-12-05 10:08 UTC, merged